# Generated by Django 5.2 on 2025-04-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('both', 'Both')], default='beginner', max_length=20),
        ),
    ]
