# Generated by Django 5.2 on 2025-05-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommunity',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('both', 'Both'), ('job_only', 'Job Only')], default='beginner', max_length=20),
        ),
    ]
