# Generated by Django 5.1.7 on 2025-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='created_by',
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='field_images/'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
