# Generated by Django 5.2 on 2025-04-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_community_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunity',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('both', 'Both')], default='beginner', max_length=20),
        ),
    ]
