# Generated by Django 5.1.7 on 2025-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_remove_field_created_by_field_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
    ]
