# Generated by Django 5.2 on 2025-04-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
