# Generated by Django 5.2 on 2025-04-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_usercommunity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='level',
        ),
    ]
