# Generated by Django 5.1.7 on 2025-04-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='jobopportunity',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='jobopportunity',
            name='type',
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.organization'),
        ),
    ]
