# Generated by Django 5.1.7 on 2025-04-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_community_image'),
        ('jobs', '0004_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.community'),
        ),
    ]
