# Generated by Django 5.1.7 on 2025-04-11 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_community_image'),
        ('jobs', '0006_alter_jobopportunity_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fields.community'),
            preserve_default=False,
        ),
    ]
