# Generated by Django 5.1.7 on 2025-04-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_community_image'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='communities',
            field=models.ManyToManyField(related_name='organizations', to='fields.community'),
        ),
    ]
