# Generated by Django 5.2 on 2025-05-07 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='communities',
            field=models.ManyToManyField(blank=True, to='fields.community'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
