# Generated by Django 5.1.7 on 2025-04-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('organization', 'Organization User'), ('admin', 'Admin')], default='normal', max_length=20),
        ),
    ]
