<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-05 23:46

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2 on 2025-05-07 15:12

import ChatRoom.models
>>>>>>> 78439836091054e64c7c509bc55485550c515c0d
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('fields', '0004_delete_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 78439836091054e64c7c509bc55485550c515c0d
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(default='Main Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='fields.community')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChatRoom',
                'verbose_name_plural': 'ChatRooms',
=======
                ('type', models.CharField(choices=[('discussion_general', 'General Discussion'), ('discussion_advanced', 'Advanced Discussion'), ('job_opportunities', 'Job Opportunities')], default='discussion_general', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=ChatRoom.models.reply_upload_path)),
                ('is_promoted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=ChatRoom.models.thread_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_job_opportunity', models.BooleanField(default=False)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(default='General', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
>>>>>>> 78439836091054e64c7c509bc55485550c515c0d
            },
        ),
    ]
