# Generated by Django 5.2 on 2025-04-10 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0002_alter_chatroom_options_thread_reply_star'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Star',
            new_name='Like',
        ),
    ]
