# Generated by Django 5.2 on 2025-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='classification',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
