# Generated by Django 5.2 on 2025-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='job_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='job_link_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direct Apply'), ('external', 'Company Page')], max_length=20, null=True),
        ),
    ]
