# Generated by Django 5.2 on 2025-05-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0003_thread_job_link_thread_job_link_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='like_target_xor',
        ),
    ]
