# Generated by Django 5.1.7 on 2025-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0003_rename_star_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='thread',
            name='is_job_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
