# Generated by Django 5.2 on 2025-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0004_alter_reply_options_alter_thread_options_reply_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
