# Generated by Django 5.2 on 2025-04-30 19:02

import ChatRoom.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0005_reply_is_promoted'),
        ('fields', '0004_remove_community_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ChatRoom.models.reply_upload_path),
        ),
        migrations.AlterField(
            model_name='thread',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=ChatRoom.models.thread_upload_path),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['community', 'type'], name='ChatRoom_ch_communi_fefdda_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', '-created_at'], name='ChatRoom_li_user_id_3836f3_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['thread', 'created_at'], name='ChatRoom_re_thread__2d0274_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['chat_room', '-created_at'], name='ChatRoom_th_chat_ro_27deae_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reply__isnull', True), ('thread__isnull', False)), models.Q(('reply__isnull', False), ('thread__isnull', True)), _connector='OR'), name='like_target_xor'),
        ),
    ]
