# Generated by Django 5.2 on 2025-04-30 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatRoom', '0006_alter_chatroom_options_alter_reply_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', True)), fields=('user', 'thread'), name='uniq_user_thread_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('thread__isnull', True)), fields=('user', 'reply'), name='uniq_user_reply_like'),
        ),
    ]
